### ISSUE TITLE
t\11-tcp-open.t hangs on MSWin32

### ISSUE THREAD

**Issue by xiaoyafeng** [genio/p5-UV#35]
I've tried on my working computer and notebook at home, both hang on open.t:

[output.txt](https://github.com/p5-UV/p5-UV/files/6256988/output.txt)

**Comment by xiaoyafeng** [comment]
Sorry for bothing, just saw the todo in open.t. but why this test doest work on windows?

**Comment by leonerd** [comment]
Latest release (1.907) won't fix the underlying problem but will stop it hanging indefinitely by hopefully killing it after a while.

As to why it doesn't work: I have no idea as I know very little about Win32 development. Do you have any suggestions?

**Comment by leonerd** [comment]
1.909 is no further closer to solving this one. Test unit test hangs *somewhere* inside it but we don't get any clear indication where, because of the SIGKILL. About the only thing I can think to try with it, is splitting the file in two pieces for the two subtests, so we can see which of the reader vs. writer side is actually failing (or both?). But I'd like to get #38 fixed first in case that is somehow related.

**Comment by leonerd** [comment]
(discussion raised at https://github.com/libuv/libuv/discussions/3239)
